import 'package:flutter_test/flutter_test.dart';

import 'package:inspectobot/features/inspection/domain/form_requirements.dart';
import 'package:inspectobot/features/inspection/domain/form_type.dart';
import 'package:inspectobot/features/inspection/domain/inspection_draft.dart';
import 'package:inspectobot/features/inspection/domain/sinkhole_form_data.dart';
import 'package:inspectobot/features/inspection/domain/sinkhole_section_definitions.dart';
import 'package:inspectobot/features/inspection/domain/universal_property_fields.dart';
import 'package:inspectobot/features/inspection/presentation/controllers/inspection_session_controller.dart';

void main() {
  group('Sinkhole Integration', () {
    late InspectionDraft draft;

    setUp(() {
      draft = InspectionDraft(
        inspectionId: 'test-sinkhole-001',
        organizationId: 'org-1',
        userId: 'user-1',
        clientName: 'Alice Doe',
        clientEmail: 'alice@test.com',
        clientPhone: '555-8888',
        propertyAddress: '789 Sinkhole Ln',
        inspectionDate: DateTime(2026, 3, 7),
        yearBuilt: 1995,
        enabledForms: {FormType.sinkholeInspection},
      );
    });

    test('setFormFieldValue stores values in draft.formData', () {
      final controller = InspectionSessionController(draft: draft);

      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'insuredName', 'Alice Doe');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'policyNumber', 'POL-12345');

      expect(draft.formData[FormType.sinkholeInspection], isNotNull);
      expect(draft.formData[FormType.sinkholeInspection]!['insuredName'],
          'Alice Doe');
      expect(draft.formData[FormType.sinkholeInspection]!['policyNumber'],
          'POL-12345');
    });

    test('tri-state field roundtrip: set Yes, verify stored', () {
      final controller = InspectionSessionController(draft: draft);

      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'ext1Depression', 'Yes');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'ext1Detail', 'Found near front yard');

      final rawData = draft.formData[FormType.sinkholeInspection]!;
      expect(rawData['ext1Depression'], 'Yes');
      expect(rawData['ext1Detail'], 'Found near front yard');
    });

    test('branch flag toggle: verify branchContext updated', () {
      final controller = InspectionSessionController(draft: draft);
      controller.initialize();

      controller.setBranchFlag(
          FormRequirements.sinkholeAnyExteriorYesBranchFlag, true);
      controller.setBranchFlag(
          FormRequirements.sinkholeTownhouseBranchFlag, false);

      final ctx = controller.snapshot.branchContext;
      expect(ctx[FormRequirements.sinkholeAnyExteriorYesBranchFlag], isTrue);
      expect(ctx[FormRequirements.sinkholeTownhouseBranchFlag], isFalse);
    });

    test('anySinkholeYes predicate: exterior=true triggers composite', () {
      final ctx = <String, dynamic>{
        FormRequirements.sinkholeAnyExteriorYesBranchFlag: true,
        FormRequirements.sinkholeAnyInteriorYesBranchFlag: false,
        FormRequirements.sinkholeAnyGarageYesBranchFlag: false,
        FormRequirements.sinkholeAnyAppurtenantYesBranchFlag: false,
      };
      expect(FormRequirements.anySinkholeYes(ctx), isTrue);
    });

    test('anySinkholeYes predicate: all false returns false', () {
      final ctx = <String, dynamic>{
        FormRequirements.sinkholeAnyExteriorYesBranchFlag: false,
        FormRequirements.sinkholeAnyInteriorYesBranchFlag: false,
        FormRequirements.sinkholeAnyGarageYesBranchFlag: false,
        FormRequirements.sinkholeAnyAppurtenantYesBranchFlag: false,
      };
      expect(FormRequirements.anySinkholeYes(ctx), isFalse);
    });

    test('scheduling attempt fields: set using RepeatingFieldGroup keys', () {
      final controller = InspectionSessionController(draft: draft);

      // Simulate keys as generated by RepeatingFieldGroup (attempt_N_Key)
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_1_Date', '2026-03-01');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_1_Time', '10:00 AM');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_1_NumberCalled', '555-1111');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_1_Result', 'No answer');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_2_Date', '2026-03-02');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_2_Time', '2:00 PM');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_2_NumberCalled', '555-2222');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_2_Result', 'Scheduled');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_3_Date', '2026-03-03');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_3_Time', '9:00 AM');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_3_NumberCalled', '555-3333');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_3_Result', 'Voicemail');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_4_Date', '2026-03-04');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_4_Time', '4:00 PM');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_4_NumberCalled', '555-4444');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_4_Result', 'Confirmed');

      final rawData = draft.formData[FormType.sinkholeInspection]!;
      expect(rawData['attempt_1_Date'], '2026-03-01');
      expect(rawData['attempt_4_Result'], 'Confirmed');
      expect(rawData.keys.where((k) => k.startsWith('attempt_')).length, 16);
    });

    test('serialization roundtrip via SinkholeFormData', () {
      final original = SinkholeFormData(
        insuredName: 'Alice Doe',
        propertyAddress: '789 Sinkhole Ln',
        policyNumber: 'POL-12345',
        inspectionDate: '2026-03-07',
        inspectorName: 'Bob Inspector',
        inspectorLicenseNumber: 'LIC-999',
        inspectorCompany: 'Inspect Co',
        inspectorPhone: '555-9876',
        ext1Depression: 'Yes',
        ext1Detail: 'Small depression near tree',
        int1DoorsOutOfPlumb: 'No',
        gar1WallToSlabCracks: 'N/A',
        app1CracksNoted: 'Yes',
        app1Detail: 'Hairline crack on patio',
        generalConditionOverview: 'Structure appears stable overall.',
        distanceToNearestSinkhole: '500 ft',
        attempt1Date: '2026-03-01',
        attempt1Time: '10:00 AM',
        attempt1NumberCalled: '555-1111',
        attempt1Result: 'No answer',
      );

      final json = original.toJson();
      final reparsed = SinkholeFormData.fromJson(json);
      expect(reparsed, equals(original));
    });

    test('toPdfMaps separates text from checkboxes, tri-state expanded', () {
      final data = SinkholeFormData(
        insuredName: 'Alice',
        ext1Depression: 'Yes',
        ext2AdjacentSinkholes: 'No',
        ext3SoilErosion: 'N/A',
        attempt1Date: '2026-03-01',
      );

      final maps = data.toPdfMaps();

      // Text fields
      expect(maps.fieldValues['insuredName'], 'Alice');
      expect(maps.fieldValues['attempt1Date'], '2026-03-01');

      // Tri-state checkboxes expanded to 3 each (double underscore)
      expect(maps.checkboxValues['ext1Depression__yes'], isTrue);
      expect(maps.checkboxValues['ext1Depression__no'], isFalse);
      expect(maps.checkboxValues['ext1Depression__na'], isFalse);

      expect(maps.checkboxValues['ext2AdjacentSinkholes__yes'], isFalse);
      expect(maps.checkboxValues['ext2AdjacentSinkholes__no'], isTrue);
      expect(maps.checkboxValues['ext2AdjacentSinkholes__na'], isFalse);

      expect(maps.checkboxValues['ext3SoilErosion__yes'], isFalse);
      expect(maps.checkboxValues['ext3SoilErosion__no'], isFalse);
      expect(maps.checkboxValues['ext3SoilErosion__na'], isTrue);

      // Tri-state keys should NOT appear as text fieldValues
      expect(maps.fieldValues.containsKey('ext1Depression'), isFalse);
    });

    test('controller remaps scheduling keys for PDF input', () {
      final controller = InspectionSessionController(draft: draft);

      // Store using RepeatingFieldGroup keys
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_1_Date', '2026-03-01');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_1_Time', '10:00 AM');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_1_NumberCalled', '555-1111');
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'attempt_1_Result', 'No answer');

      // Verify the remapping via static helper on SinkholeFormData
      final rawData = draft.formData[FormType.sinkholeInspection]!;
      final remapped = SinkholeFormData.remapSchedulingKeys(rawData);

      expect(remapped['attempt1Date'], '2026-03-01');
      expect(remapped['attempt1Time'], '10:00 AM');
      expect(remapped['attempt1NumberCalled'], '555-1111');
      expect(remapped['attempt1Result'], 'No answer');

      // Non-scheduling keys pass through
      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'insuredName', 'Alice');
      final remapped2 = SinkholeFormData.remapSchedulingKeys(
          draft.formData[FormType.sinkholeInspection]!);
      expect(remapped2['insuredName'], 'Alice');
    });

    test('withDefaults pre-fills universal fields', () {
      final universal = UniversalPropertyFields(
        propertyAddress: '789 Sinkhole Ln',
        inspectionDate: DateTime(2026, 3, 7),
        inspectorName: 'Bob Inspector',
        inspectorCompany: 'Inspect Co',
        inspectorLicenseNumber: 'LIC-999',
        clientName: 'Alice Doe',
      );

      final data = SinkholeFormData.withDefaults(universal: universal);

      expect(data.insuredName, 'Alice Doe');
      expect(data.propertyAddress, '789 Sinkhole Ln');
      expect(data.inspectionDate, '2026-03-07');
      expect(data.inspectorName, 'Bob Inspector');
      expect(data.inspectorCompany, 'Inspect Co');
      expect(data.inspectorLicenseNumber, 'LIC-999');
    });

    test('section definitions have correct structure', () {
      final sections = SinkholeSectionDefinitions.all;
      expect(sections.length, 7);

      // Property ID has 8 standalone fields, no groups
      expect(sections[0].fieldDefinitions.length, 8);
      expect(sections[0].fieldGroups.length, 0);

      // Exterior has 5 field groups, no standalone fields
      expect(sections[1].fieldDefinitions.length, 0);
      expect(sections[1].fieldGroups.length, 5);

      // Interior has 8 field groups
      expect(sections[2].fieldGroups.length, 8);

      // Garage has 2 field groups
      expect(sections[3].fieldGroups.length, 2);

      // Appurtenant has 4 field groups
      expect(sections[4].fieldGroups.length, 4);

      // Additional has 5 standalone fields
      expect(sections[5].fieldDefinitions.length, 5);

      // Scheduling has 1 repeating field group with 4 repetitions
      expect(sections[6].repeatingFieldGroups.length, 1);
      expect(sections[6].repeatingFieldGroups[0].repetitions, 4);

      // Total field count = 67
      expect(SinkholeSectionDefinitions.totalFieldCount, 67);
    });

    test('onStateChanged fires on setFormFieldValue', () {
      final controller = InspectionSessionController(draft: draft);
      var callCount = 0;
      controller.onStateChanged = () => callCount++;

      controller.setFormFieldValue(
          FormType.sinkholeInspection, 'insuredName', 'Test');

      expect(callCount, 1);
    });
  });
}
