import 'dart:typed_data';

import 'package:pdf/widgets.dart' as pw;

import 'narrative_print_theme.dart';
import 'narrative_render_context.dart';
import 'narrative_template.dart';

/// Renders a [NarrativeTemplate] into a PDF document.
///
/// Builds sections from the template, renders each into PDF widgets,
/// then assembles them into a [pw.MultiPage] with consistent headers
/// and footers.
class NarrativePdfRenderer {
  const NarrativePdfRenderer();

  /// Renders the template into PDF bytes.
  ///
  /// Returns the raw PDF file content as [Uint8List].
  Future<Uint8List> render({
    required NarrativeTemplate template,
    required NarrativePrintTheme theme,
    required NarrativeRenderContext context,
    required Map<String, dynamic> formData,
    required Map<String, dynamic> branchContext,
  }) async {
    final sections = template.buildSections(
      formData: formData,
      branchContext: branchContext,
    );

    final widgets = <pw.Widget>[];
    for (final section in sections) {
      widgets.addAll(section.render(theme: theme, context: context));
    }

    final document = pw.Document();
    document.addPage(
      pw.MultiPage(
        pageFormat: theme.pageFormat,
        margin: theme.pageMargin,
        header: (pwContext) => _buildPageHeader(theme, template, pwContext),
        footer: (pwContext) => _buildPageFooter(theme, template, pwContext),
        build: (pwContext) => widgets,
      ),
    );

    return document.save();
  }

  /// Compact header for pages 2+. Page 1 returns an empty box so the
  /// template's own [HeaderSection] controls the first-page appearance.
  pw.Widget _buildPageHeader(
    NarrativePrintTheme theme,
    NarrativeTemplate template,
    pw.Context pwContext,
  ) {
    // Page 1 — no header (the template's HeaderSection handles it)
    if (pwContext.pageNumber == 1) {
      return pw.SizedBox(height: 0);
    }

    // Pages 2+ — title text with an accent underline
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(template.title, style: theme.captionStyle),
        pw.SizedBox(height: 2),
        pw.Container(height: 1, color: theme.accentPrimary),
        pw.SizedBox(height: 8),
      ],
    );
  }

  /// Footer on every page: thin divider, then revision label on the left,
  /// "Generated by InspectoBot" centered, and "Page X of Y" on the right.
  pw.Widget _buildPageFooter(
    NarrativePrintTheme theme,
    NarrativeTemplate template,
    pw.Context pwContext,
  ) {
    return pw.Column(
      children: [
        pw.SizedBox(height: 4),
        pw.Container(
          height: 0.5,
          color: theme.divider,
        ),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(template.revisionLabel, style: theme.footerStyle),
            pw.Text('Generated by InspectoBot', style: theme.footerStyle),
            pw.Text(
              'Page ${pwContext.pageNumber} of ${pwContext.pagesCount}',
              style: theme.footerStyle,
            ),
          ],
        ),
      ],
    );
  }
}
